name: cartoon_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.2.2
  flutter_staggered_grid_view:
  firebase_core: ^1.3.0
  cached_network_image: ^3.0.0
  permission_handler: ^8.1.2
  image_gallery_saver: ^1.6.9
  path_provider: ^2.0.2
  dio: ^4.0.0
  font_awesome_flutter: ^10.1.0
  material_design_icons_flutter: ^5.0.6595

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
        - asset: assets/fonts/GoogleSans-Regular.ttf

